---
version: "2"
linters:
  default: standard
  enable:
    - usetesting
    - testpackage
    - testifylint
    - tagalign
formatters:
  enable: [ gci, gofmt, gofumpt, goimports ]
run:
  tests: true
  timeout: 5m
